### ISSUE TITLE
Didn't see any other way to directly contact you.

### ISSUE THREAD

**Issue by DefaultO** [TheLeftExit/TeslaX#1]
I'd love to fork the memory-based project. Since I have planned some things for it. But I highly doubt your pointers will work nowadays. Because a lot was changed in those 9 months.

        public static short GetBlock(this ProcessHandle handle, int x, int y)
        {
            int lastoffset = 0x04 + x * 0x80 + y * 0x3200;
            byte[] rawx = handle.GetBytes(0x4EEEF8, 2, 0xCC8, 0x130, 0x28, lastoffset);
            return BitConverter.ToInt16(rawx, 0);
        }

        public static short GetBackground(this ProcessHandle handle, int x, int y)
        {
            int lastoffset = 0x06 + x * 0x80 + y * 0x3200;
            byte[] rawx = handle.GetBytes(0x4EEEF8, 2, 0xCC8, 0x130, 0x28, lastoffset);
            return BitConverter.ToInt16(rawx, 0);
        }
Based on your code I guess I can retrieve the whole worlds placed blocks information (including trees!) by looping through every block in the world. Since all the worlds do have the same size, this shouldn't be a problem. I would then try to code a pathfinding Bot with the Worlds Information because you also gave us a method to get the players X and Y position.

> I wonder if you can do that with dropped items too?

But I got a more serious question since I failed to get the player's position through looking for increased/decreased values based on the info you get when wrenching yourself. **How did you find those Pointers? What have you done, to get them?** I wouldn't call me a noob in using Cheat Engine. But I am not able to find coordinates of the player(s), that you can keep using even after re-entering the world. Would appreciate, to get an answer, nothing too much detailed, if you are still actively using your GitHub Account or rather check-in once in a while.

I think getting the Zoom Factor, to send mouse clicks to a block's position in different rows, instead of the punch button is also possible. But I will try to find that one, myself.

_This project I would want to work on is just for learning purposes since I never have done anything pathfinding related with a few possible states (solid block, platform, empty space and combining that with a jump/double jump and the simple movement of the game) and I will upload it to GitHub or create a pull request to your repos if you want that._

**Comment by TheLeftExit** [comment]
Hi, I actually abandoned the project since I lost all interest in the game itself, but I'm glad to help.

All values that are used are located with multi-level pointers. For example, when you find the 4 values that represent the X coordinate, you ditch the 2 that update less frequently, then use the "What accesses this address" tool from right-clicking the address. Then find addresses that access yours often enough, search those addresses as hex values, and repeat the process until the address is static. "Multi-level pointer" tutorials should help you out, the specific issue in this case is choosing the right pointer from the many you'll find.

I won't be able to access the game and get you the current values myself for a month or so, so do try playing around with CE. This pointer hunt was my first complex experience with it as well.

**Comment by TheLeftExit** [comment]
The X/Y coordinate is not the value you see when you wrench yourself, it's the difference in pixels between your character's leftmost (topmost) position and its current one.

**Comment by bexpg000** [comment]
> The X/Y coordinate is not the value you see when you wrench yourself, it's the difference in pixels between your character's leftmost (topmost) position and its current one.

wow u still alive?

**Comment by DefaultO** [comment]
@TheLeftExit no problem. Take your time. I really need help only with the current block position of the player. World Data seems to be easy to get. Unless you got an easier way to find it, you don't have to help me with it.

Steps for anyone else who wants to find it (information from @ma):
1. Go to the top left world.
2. Place dirt for example, search 1.
3. Break it, search 0.
4. Repeat until you find only 1 memory address with that value.
5. Right-click it / select it and go to the memory view.
6. Break and trace and get Register with the block value.

**Comment by DefaultO** [comment]
> The X/Y coordinate is not the value you see when you wrench yourself, it's the difference in pixels between your character's leftmost (topmost) position and its current one.

Oh. So it's this 3???px (width) / 2???px (height)? I already have that one, I thought you have a way to get the current block position (similar to what you see when you wrench yourself). Using math and adding the player width / 2 & height / 2 (to have the center of the player) to the current pixel world position and dividing it horizontally with 32px and vertically with 41px is not accurate.

**Comment by TheLeftExit** [comment]
> > The X/Y coordinate is not the value you see when you wrench yourself, it's the difference in pixels between your character's leftmost (topmost) position and its current one.
> 
> Oh. So it's this 3???px (width) / 2???px (height)? I already have that one, I thought you have a way to get the current block position (similar to what you see when you wrench yourself). Using math and adding the player width / 2 & height / 2 (to have the center of the player) to the current pixel world position and dividing it horizontally with 32px (~ player width) and vertically with 41px (~ player height) is not accurate.
> 
> Edit: I am off by one or multiple blocks doing so.

Player's width is 20, height is 30. And those values aren't used in game's calculations, it just divides both pixel coordinates by 32 and adds 1. Just checked that.

**Comment by DefaultO** [comment]
> > > The X/Y coordinate is not the value you see when you wrench yourself, it's the difference in pixels between your character's leftmost (topmost) position and its current one.
> > 
> > 
> > Oh. So it's this 3???px (width) / 2???px (height)? I already have that one, I thought you have a way to get the current block position (similar to what you see when you wrench yourself). Using math and adding the player width / 2 & height / 2 (to have the center of the player) to the current pixel world position and dividing it horizontally with 32px (~ player width) and vertically with 41px (~ player height) is not accurate.
> > Edit: I am off by one or multiple blocks doing so.
> 
> Player's width is 20, height is 30 (for collision). And those values aren't used in game's calculations, it simply divides both pixel coordinates by 32 and adds 1. Just checked that.

I will try it again then when I am back at home. This is what I had so far. Using multi-boxing and smart process management I could make usually long-taking tasks like the world nuking a lot faster by having more minions work it down. Syncing them shouldn't be a problem. Also, there is still air up for optimization. I need the current block position tho, to make it that good. 

Your project was the best I found and was the best until I started developing my "kekma" (baritone for gt) project. You have earned my respect for being the first. Thank you. And if your current block pos calculation is working I owe you something. Even though I am pretty sure I tried it that way, and it was still inaccurate (which why I build in getting the center of the player for the calculation - because it seemed to be smarter for getting the current block your player is standing at, I can't actually believe they don't do it that way).

### Pathfinding to lava blocks (hardcoded):
https://www.youtube.com/watch?v=JV59vJp5kSs
### Nuking Worlds:
![1](https://user-images.githubusercontent.com/42414542/99956767-d6f24000-2d86-11eb-91d8-a58858d64119.gif)

**Comment by TheLeftExit** [comment]
> ### Nuking Worlds

Why didn't you mention it sooner? Once you:

- recode it to work with multiple blocks at once instead of just one (just compare more block/BG IDs),
- write a proper end-of-row script (don't even need to change the code, there's user interface for that),
- add scenarios for breaking-replacing lava,

you can pretty much use my project to clear entire worlds. `GetNextBlockInfo()` should allow that.

In any case, I'll get to doing that once I'm able to,_cough, serving in the army until the end of December, cough._

**Comment by DefaultO** [comment]
> > ### Nuking Worlds
> 
> Why didn't you mention it sooner? Once you:
> 
> * recode it to work with multiple blocks at once instead of just one (just compare more block/BG IDs),
> * write a proper end-of-row script (don't even need to change the code, there's user interface for that),
> * add scenarios for breaking-replacing lava,
> 
> you can pretty much use my project to clear entire worlds. [`GetNextBlockInfo()`](https://www.github.com/TheLeftExit/TeslaX/tree/memory-based/TeslaX%2FStatic%2FWorkflow%2FWorkflow.Methods.cs) should allow that. It just seeks for the first block in a straight line in front of the player, returns its FG/BG ID and distance to it.
> 
> In any case, I'll get to doing that once I'm able to, _cough, serving in the army until the end of December, cough._

Well. It's not only meant for breaking entire worlds. Which gets hard because of the 5 high lava area. I want to expand it to work with my 100+ Chandelier Farms. Auto Harvesting the trees using tractors and auto planting using plow. And that fully automatic with 10 Bots (for the beginning). From there on the horizon is the only end to this. Maybe making it packet based afterwards. 

But I see. You know how it goes. :'D
